### ISSUE TITLE
[NB-System-Properties] Add the possibility to set/modify the system variables 

### ISSUE THREAD

**Issue by Git-GT** [manikantannaren/mynetbeans#12]
Hi,
could you add the possibility to also set or modify the system variable other than read them?
Thanks and best regards

**Comment by manikantannaren** [comment]
I don't think Changing the OS env variable from a Java process  is a good idea. This puts a dependency on native OS flavour.

**Comment by Chris2011** [comment]
Why not? I mean you can check whether all or some can be changed and then change it. Show a warning/info that you should do it in your own risk.

The other part is, that you not only show the OS system properties, you also show the NetBeans system props, which defintely should be changable in your plugin.

**Comment by Chris2011** [comment]
Would be great enhancement :)

**Comment by manikantannaren** [comment]
I agree that it would be a nice enhancmenet and I had started the plugin with the intent of editing props but gave up on the edit option since these properties are coming from multiple places. 
 I am relying on Java to provide them to me via System.getProperties and System.getEnv and I do not have a direct way to locate the source of these props. 

for example, the netbeans properties come from the startup command line and from the netbeans.conf file - both these files I could not find a way of locating them from within the plugin.
